export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'

export const DISPLAY_JOB_DESCRIPTION = 'DISPLAY_JOB_DESCRIPTION'

export const SET_INITIAL_FILTERED_DATA = 'SET_INITIAL_FILTERED_DATA'

export const FILTER_DATA = 'FILTER_DATA'
export const FILTER_DATA_REMOTE = 'FILTER_DATA_REMOTE'
export const FILTER_BY_REMOTE_ONSITE_ALL = 'FILTER_BY_REMOTE_ONSITE_ALL'
export const FILTER_BY_REMOTE_ONLY = 'FILTER_BY_REMOTE_ONLY'
export const FILTER_BY_ONSITE_ONLY = 'FILTER_BY_ONSITE_ONLY'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const EDIT_JOB = 'EDIT_JOB'
export const CANCEL_EDIT_JOB = 'CANCEL_EDIT_JOB'
export const SUBMIT_EDIT_JOB = 'SUBMIT_EDIT_JOB'